import 'package:get/get.dart';

class Localstring extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'No Internet Connection': 'No Internet Connection',
          'Internet Connection Available': 'Internet Connection Available',
          'Live Programs': 'Live Programs',
          'About Hurriyet': 'About Hurriyet',
          'At Hurriyet, we are dedicated to bringing you the latest, most accurate, and compelling news stories. We understand the power of information in shaping opinions, fostering informed discussions, and driving positive change in our communities. Our mission is to provide you with news that matters, with integrity, impartiality, and a commitment to the highest journalistic standards.':
              'At Hurriyet, we are dedicated to bringing you the latest, most accurate, and compelling news stories. We understand the power of information in shaping opinions, fostering informed discussions, and driving positive change in our communities. Our mission is to provide you with news that matters, with integrity, impartiality, and a commitment to the highest journalistic standards.',
          'Our Objectives': 'Our Objectives',
          'Objectives include expanding coverage, engaging the audience, enhancing digital presence, and nurturing our dedicated team.':
              'Objectives include expanding coverage, engaging the audience, enhancing digital presence, and nurturing our dedicated team.',
          'Our Mission': 'Our Mission',
          'We provide accurate, impartial news to inspire dialogue and empower decision-making.':
              'We provide accurate, impartial news to inspire dialogue and empower decision-making.',
          'Our Vision': 'Our Vision',
          'Our vision is to be a trusted source of news, fostering an informed and connected world.':
              'Our vision is to be a trusted source of news, fostering an informed and connected world.',
          'Our Goal': 'Our Goal',
          'Our goals at Hurriyet focus on truth, diversity, community, and innovation.':
              'Our goals at Hurriyet focus on truth, diversity, community, and innovation.',
          'Are you sure?': 'Are you sure?',
          'Do you want to remove the item?': 'Do you want to remove the item?',
          'Yes': 'Yes',
          'No': 'No',
          'News Have Been deleted': 'News Have Been deleted',
          'News Has Been Added!': 'News Has Been Added!',
          '     No Data Availabe! \n Please Try Again Later.':
              '     No Data Availabe! \n Please Try Again Later.',
          'Video News': 'Video News',
          'Analysis': 'Analysis',
          'Latest Analysis': 'Latest Analysis',
          'Documentaries': 'Documentaries',
          'Latest Documentaries': 'Latest Documentaries',
          'Latest Reports': 'Latest Reports',
          'Radio Programs': 'Radio Programs',
          'All Programs': 'All Programs',
          'Latest Programs': 'Latest Programs',
          'Search Here...': 'Search Here...',
          'ُView All': 'View All',
          'Reports': 'Reports',
          'Afghanistan': 'Afghanistan',
          'World': 'World',
          'Asia': 'Asia',
          'Politics': 'Politics',
          'Development': 'Development',
          'Islam & Culture': 'Islam & Culture',
          'Technology': 'Technology',
          'Hurriyat': 'Hurriyat',
          'News': 'News',
          'Arabic': 'Arabic',
          'Resource:': 'Resource:',
          'Business': 'Business',
          'ُTrending News': 'Trending News',
          'ُBreaking News': 'Breaking News',
          'Faham Community': 'Faham Community',
          'Become Our Members': 'Become Our Members',
          'PUBLISHED IN': 'PUBLISHED IN',
          'In': 'In',
          'Enter a valid email': 'Enter a valid email',
          'Please Wait....': 'Please Wait....',
          'Favorites': 'Favorites',
          'Create New Post': 'Create New Post',
          'Choose Profile photo': 'Choose Profile photo',
          'Home': 'Home',
          'Posts': 'Posts',
          'Members': 'Members',
          'Invite Friends': 'Invite Friends',
          'Language': 'Language',
          'English': 'English',
          'Pashto': 'Pashto',
          'Dari': 'Dari',
          'Dark Mood': 'Dark Mood',
          'Light Mood': 'Light Mood',
          'Privacy': 'Privacy',
          'Policy': 'Policy',
          'About Us': 'About Us',
          'Log Out': 'log Out',
          'Login': 'Login',
          'Sign up': 'Sign up',
          'Faham': 'Faham',
          'Public': 'public',
          'Sports': 'Sports',
          'Motivation': 'Motivation',
          'Health': 'Health',
          'Political': 'Political',
          'loves': 'loves',
          'Shares': 'Shares',
          'Views': 'Views',
          'Name': 'Name',
          'Enter Name:': 'Enter Name:',
          'password': 'password',
          'Movie': 'Movie',
          'Foods': 'Foods',
          'Religious': 'Religious',
          'Economic': 'Economic',
          'History': 'History',
          'Geographical': 'Geographical',
          'Do you have account?': 'Do you have account?',
          'Does not have account yet?': 'Does not have account yet?',
          'password': 'password',
          'Enter Password': 'Enter Password',
          'Sign Up Form': 'Sign Up Form',
          'First Name': 'First Name',
          'Enter First Name': 'Enter First Name',
          'last Name': 'last Name',
          'Enter Last Name:': 'Enter last Name:',
          'Email': 'Email',
          'Enter User Email:': 'Enter User Email:',
          'َBio': 'Bio',
          'Enter Your Biography:': 'Enter Your Biography:',
          'َJob': 'Job',
          'Enter Your Job:': 'Enter Your Job:',
          'َStatues': 'Statues',
          'Enter Your Statues:': 'Enter Your Statues:',
          'Confirm Password': 'Confirm password',
          'Camera': 'Camera',
          'Gallery': 'Gallery',
          'Sign Up': 'Sign Up',
          'Login In': 'Login In',
          'Log in Form ': 'Login in Form',
        },
        // 'ar_AR': {
        //   'About Hurriyet': 'عن الحريات',
        // },
        'arr_ARR': {
          'No Internet Connection': 'لا یوجد اتصال بالاٍنترنیت',
          'Internet Connection Available': 'اتصال بالاٍنترنیت متاح',
          'Live Programs': 'برامج حیة',
          'About Hurriyet': 'عن الحريات',
          'At Hurriyet, we are dedicated to bringing you the latest, most accurate, and compelling news stories. We understand the power of information in shaping opinions, fostering informed discussions, and driving positive change in our communities. Our mission is to provide you with news that matters, with integrity, impartiality, and a commitment to the highest journalistic standards.':
              'في حريت، نحن ملتزمون بتقديم أحدث الأخبار وأكثرها دقة وإقناعًا.  نحن نفهم قوة المعلومات في تشكيل الآراء، وتعزيز المناقشات المستنيرة، وقيادة التغيير الإيجابي في مجتمعاتنا.  مهمتنا هي تزويدك بالأخبار التي تهمك بنزاهة وحيادية والالتزام بأعلى المعايير الصحفية.',
          'Our Objectives': 'أهدافنا',
          'Objectives include expanding coverage, engaging the audience, enhancing digital presence, and nurturing our dedicated team.':
              ' تشمل الأهداف توسيع التغطية وإشراك الجمهور وتعزيز الحضور الرقمي ورعاية فريقنا المتفاني.',
          'Our Mission': 'مهمتنا',
          'We provide accurate, impartial news to inspire dialogue and empower decision-making.':
              ' نحن نقدم أخبارًا دقيقة ومحايدة لإلهام الحوار وتمكين اتخاذ القرار.',
          'Our Vision': 'رؤيتنا',
          'Our vision is to be a trusted source of news, fostering an informed and connected world.':
              ' رؤيتنا هي أن نكون مصدرا موثوقا للأخبار، وتعزيز عالم مستنير ومتصل.',
          'Our Goal': 'هدفنا',
          'Our goals at Hurriyet focus on truth, diversity, community, and innovation.':
              ' تركز أهدافنا في حريت على الحقيقة والتنوع والمجتمع والابتكار.',
          'Are you sure?': 'ایا ته باوري یې؟',
          'Do you want to remove the item?': 'ایا ته غواړې خبر ختم کړې؟',
          'Yes': 'هو',
          'No': 'نه',
          'News Have Been deleted': '!خبر ړنګ شو',
          'News Has Been Added!': '.خبر اضافه شو',
          '     No Data Availabe! \n Please Try Again Later.':
              '                !لا تتوافر بيانات \n الرجاء معاودة المحاولة في وقت لاحق.',
          'Video News': 'أخبار الفيديو',
          'Analysis': 'تحليل',
          'Latest Analysis': ' أحدث التحليلات',
          'Documentaries': 'الافلام الوثائقية',
          'Latest Documentaries': 'أحدث الأفلام الوثائقية',
          'Latest Reports': 'حدث التقارير',
          'Radio Programs': 'البرامج مذياع',
          'All Programs': 'كل البرامج',
          'Latest Programs': 'أحدث البرامج',
          'Reports': 'التقارير',
          'Search Here...': 'ابحث هنا...',
          'Business': 'عمل',
          'Afghanistan': 'أفغانستان',
          'World': 'عالم',
          'Asia': 'آسيا',
          'Politics': 'سياسة',
          'Development': 'تطوير',
          'Islam & Culture': 'الإسلام والثقافة',
          'Technology': 'تكنولوجيا',
          'News': 'أخبار',
          'Hurriyat': 'حوریت',
          'Arabic': 'عربي',
          'Resource:': ':سرچینه',
          'ُTrending News': 'الأخبار الشائعة',
          'ُBreaking News': 'أخبار عاجلة',
          'ُView All': 'ټول لیدل',
          'Become Our Members': 'زمونږ ملګري شئ',
          'Privacy': 'امنیت',
          'Policy': 'تګلاره',
          'Faham Community': 'Faham Community',
          'PUBLISHED IN': 'خپور شوی په',
          'In': 'په',
          'Enter a valid email': 'صحي ایمیل ادرس داخیل کړئ',
          'Please Wait....': 'لږ صبر وکړئ',
          'Create New Post': 'نوې فوسټ وکړئ',
          'Log in Form ': 'داخلیدلو فورم',
          'Sign Up': 'نوی جوړول',
          'Login In': 'داخلیدل',
          'Camera': 'کېمره',
          'Gallery': 'صالة عرض',
          'Confirm Password': 'د پټ نوم صحی کول',
          'َStatues': 'حالت',
          'Enter Your Statues:': 'خپل حالت وليکئ',
          'َJob': 'دنده',
          'Enter Your Job:': 'خپله دنده ولیکئ',
          'َBio': 'پیژند',
          'Enter Your Biography:': 'خپل پیژند ولیکئ',
          'Email': 'ایمل ادرس',
          'Enter User Email:': 'ایمل ادرس داخیل کړئ',
          'last Name': 'اخر نوم',
          'Enter Last Name:': 'اخر نوم ولیکئ',
          'Enter First Name': 'لومړی نوم ولیکئ',
          'First Name': 'لومړی نوم',
          'Sign Up Form': 'د نوي اکونټ جوړیدلو فورم',
          'Enter Password': 'پټ نوم داخل کړئ',
          'password': 'پټ نوم',
          'Does not have account yet?': 'ایا اکونټ نلرئ؟',
          'Do you have account?': 'ایا اکونټ لرئ؟',
          'Choose Profile photo': 'خپل انځور غوره ګړئ',
          'Movie': 'سینما',
          'Foods': 'خوراک',
          'Religious': 'مذهب',
          'Economic': 'اقتصاد',
          'Historical': 'تاریخ',
          'Geographical': 'جغرافیه',
          'Enter Name:': 'خپل ایمیل ادرس وليکئ',
          'Favorites': 'المفضلة',
          'Posts': 'اعلانات',
          'Home': 'کور',
          'Members': 'استعمالونکي',
          'Invite Friends': 'ملګري دعوت کړئ',
          'Language': 'لسان',
          'English': 'انګلش',
          'Pashto': 'پښتو',
          'Dari': ' دری',
          'Dark Mood': 'تیاره حالت',
          'Light Mood': 'روښانه حالت',
          'Help': 'مرسته',
          'FeedBack': 'بیا کتنه',
          'About Us': 'معلومات عنا',
          'Log Out': 'بهر کېدل',
          'Login': 'ننوتل',
          'Sign up': 'نوی جوړول',
          'Faham': 'فهم',
          'Public': 'عام',
          'Sports': 'رياضات',
          'Motivation': 'انګېزیشي',
          'Health': 'صحة',
          'Political': 'سیاسي',
          'loves': 'خوښول',
          'Shares': 'خپرول',
          'Views': 'المشاهدین',
          'Name': 'نوم',
        },
        'pa_AF': {
          'No Internet Connection': 'سرور ځواب نه وايي ښايي افلاین یاستئ',
          'Internet Connection Available': 'ستاسو ټېلفون له انټرنیت سره وصل ده',
          'Live Programs': 'ژوندۍ خپرونې',
          'About Hurriyet': 'د حریت په اړه',
          'At Hurriyet, we are dedicated to bringing you the latest, most accurate, and compelling news stories. We understand the power of information in shaping opinions, fostering informed discussions, and driving positive change in our communities. Our mission is to provide you with news that matters, with integrity, impartiality, and a commitment to the highest journalistic standards.':
              'په حریت کې، موږ تاسو ته د وروستي، خورا کره او زړه راښکونکو خبرونو راوړو لپاره وقف شوي یو.  موږ د نظرونو په جوړولو، باخبره بحثونو ته وده ورکولو، او په ټولنه کې د مثبت بدلون په لاره اچولو کې د معلوماتو په ځواک پوهیږو.  زموږ دنده دا ده چې تاسو ته هغه خبرونه وړاندې کړو کوم چې مهم دي، په صداقت، بې پرېتوب او لوړ ژورنالیستیکي معیارونو ته ژمنتیا.',
          'Our Objectives': 'زموږ موخې',
          'Objectives include expanding coverage, engaging the audience, enhancing digital presence, and nurturing our dedicated team.':
              'په اهدافو کې د پوښښ پراخول، د لیدونکو ښکیلول، د ډیجیټل شتون لوړول، او زموږ د وقف شوي ټیم پالنه شامل دي.',
          'Our Mission': 'زموږ ماموریت',
          'We provide accurate, impartial news to inspire dialogue and empower decision-making.':
              ' موږ د خبرو اترو هڅولو او تصمیم نیولو ځواکمنولو لپاره دقیق، بې طرفه خبرونه چمتو کوو.',
          'Our Vision': 'زموږ لید',
          'Our vision is to be a trusted source of news, fostering an informed and connected world.':
              'زموږ لید دا دی چې د خبرونو باوري سرچینه واوسو، او یوې باخبره او تړلې نړۍ نه وده ورکول.',
          'Our Goal': 'زموږ هدف',
          'Our goals at Hurriyet focus on truth, diversity, community, and innovation.':
              'په حریت کې زموږ اهداف په حقیقت، تنوع، ټولنې او نوښت تمرکز کوي.',
          'Are you sure?': 'ایا ته باوري یې؟',
          'Do you want to remove the item?': 'ایا ته غواړې خبر ختم کړې؟',
          'Yes': 'هو',
          'No': 'نه',
          'News Have Been deleted': '!خبر ړنګ شو',
          'News Has Been Added!': '.خبر اضافه شو',
          '     No Data Availabe! \n Please Try Again Later.':
              '    !معلومات وجود نلري \n مهرباني وکړئ بیا هڅه وکړئ.',
          'Video News': 'ویډیوي خبرونه',
          'Analysis': 'بحثونه',
          'Latest Analysis': 'وروستي بحثونه',
          'Documentaries': 'مستند',
          'Latest Documentaries': 'وروستي مستند',
          'Latest Reports': 'وروستي راپورونه',
          'Radio Programs': 'راډیوي خپرونې',
          'All Programs': 'ټولې خپرونې',
          'Latest Programs': 'وروستۍ خپرونې',
          'Reports': 'راپورونه',
          'Search Here...': 'دلته لټون وکړئ',
          'Business': 'تجارت',
          'Afghanistan': 'افغانستان',
          'World': 'نړۍ',
          'Asia': 'اسیاّ',
          'Politics': 'سیاست',
          'Development': 'پرمختګ',
          'Islam & Culture': 'اسلام او کلتور',
          'Technology': 'تخنیک پوهنه',
          'News': 'خبرونه',
          'Hurriyat': 'حوریت',
          'Arabic': 'عربي',
          'Resource:': ':سرچینه',
          'ُTrending News': 'عاجل خبرونه',
          'ُBreaking News': 'عام خبرونه',
          'ُView All': 'ټول لیدل',
          'Become Our Members': 'زمونږ ملګري شئ',
          'Privacy': 'امنیت',
          'Policy': 'تګلاره',
          'Faham Community': 'Faham Community',
          'PUBLISHED IN': 'خپور شوی په',
          'In': 'په',
          'Enter a valid email': 'صحي ایمیل ادرس داخیل کړئ',
          'Please Wait....': 'لږ صبر وکړئ',
          'Create New Post': 'نوې فوسټ وکړئ',
          'Log in Form ': 'داخلیدلو فورم',
          'Sign Up': 'نوی جوړول',
          'Login In': 'داخلیدل',
          'Camera': 'کېمره',
          'Gallery': 'ګالري',
          'Confirm Password': 'د پټ نوم صحی کول',
          'َStatues': 'حالت',
          'Enter Your Statues:': 'خپل حالت وليکئ',
          'َJob': 'دنده',
          'Enter Your Job:': 'خپله دنده ولیکئ',
          'َBio': 'پیژند',
          'Enter Your Biography:': 'خپل پیژند ولیکئ',
          'Email': 'ایمل ادرس',
          'Enter User Email:': 'ایمل ادرس داخیل کړئ',
          'last Name': 'اخر نوم',
          'Enter Last Name:': 'اخر نوم ولیکئ',
          'Enter First Name': 'لومړی نوم ولیکئ',
          'First Name': 'لومړی نوم',
          'Sign Up Form': 'د نوي اکونټ جوړیدلو فورم',
          'Enter Password': 'پټ نوم داخل کړئ',
          'password': 'پټ نوم',
          'Does not have account yet?': 'ایا اکونټ نلرئ؟',
          'Do you have account?': 'ایا اکونټ لرئ؟',
          'Choose Profile photo': 'خپل انځور غوره ګړئ',
          'Movie': 'سینما',
          'Foods': 'خوراک',
          'Religious': 'مذهب',
          'Economic': 'اقتصاد',
          'Historical': 'تاریخ',
          'Geographical': 'جغرافیه',
          'Enter Name:': 'خپل ایمیل ادرس وليکئ',
          'Favorites': 'نښه شوي',
          'Posts': 'اعلانات',
          'Home': 'کور',
          'Members': 'استعمالونکي',
          'Invite Friends': 'ملګري دعوت کړئ',
          'Language': 'ژبې',
          'English': 'انګلش',
          'Pashto': 'پښتو',
          'Dari': ' دری',
          'Dark Mood': 'تیاره حالت',
          'Light Mood': 'روښانه حالت',
          'Help': 'مرسته',
          'FeedBack': 'بیا کتنه',
          'About Us': 'زمونږ په اړه',
          'Log Out': 'بهر کېدل',
          'Login': 'ننوتل',
          'Sign up': 'نوی جوړول',
          'Faham': 'فهم',
          'Public': 'عام',
          'Sports': 'لوبې',
          'Motivation': 'انګېزیشي',
          'Health': 'روغتیا',
          'Political': 'سیاست',
          'loves': 'خوښول',
          'Shares': 'خپرول',
          'Views': 'لیدونکي',
          'Name': 'نوم',
        },
        'dr_Af': {
          'No Internet Connection': 'تلیفون شما به انترنیت وصل نیست',
          'Internet Connection Available': 'تلیفون شما به انترنیت وصل نیست',
          'Live Programs': 'برنامه های زنده',
          'About Hurriyet': 'در باره حریت',
          'At Hurriyet, we are dedicated to bringing you the latest, most accurate, and compelling news stories. We understand the power of information in shaping opinions, fostering informed discussions, and driving positive change in our communities. Our mission is to provide you with news that matters, with integrity, impartiality, and a commitment to the highest journalistic standards.':
              'در حریت، ما به ارائه جدیدترین، دقیق‌ترین و قانع‌کننده‌ترین اخبار برای شما اختصاص داریم.  ما قدرت اطلاعات را در شکل دادن به نظرات، پرورش بحث های آگاهانه و ایجاد تغییرات مثبت در جوامع خود درک می کنیم.  ماموریت ما ارائه اخبار مهم، صداقت، بی طرفی و تعهد به بالاترین استانداردهای روزنامه نگاری است.',
          'Our Objectives': 'اهداف ما',
          'Objectives include expanding coverage, engaging the audience, enhancing digital presence, and nurturing our dedicated team.':
              ' اهداف شامل گسترش پوشش، جذب مخاطب، افزایش الأخبار الشائعة حضور دیجیتال و پرورش تیم اختصاصی ما است.',
          'Our Mission': 'ماموریت ما ',
          'We provide accurate, impartial news to inspire dialogue and empower decision-making.':
              ' ما اخبار دقیق و بی طرفانه ای را برای الهام بخشیدن به گفتگو و توانمندسازی تصمیم گیری ارائه می دهیم.',
          'Our Vision': 'دیدگاه ما',
          'Our vision is to be a trusted source of news, fostering an informed and connected world.':
              'چشم انداز ما این است که منبع اخبار قابل اعتمادی باشیم و دنیایی آگاه و متصل را تقویت کنیم.',
          'Our Goal': 'هدف ما',
          'Our goals at Hurriyet focus on truth, diversity, community, and innovation.':
              'اهداف ما در حریت بر حقیقت، تنوع، اجتماع و نوآوری متمرکز است.',
          'Are you sure?': 'ایا شما باور داری؟',
          'Do you want to remove the item?': 'ایا میخواهی خبر ختم را کنید؟',
          'Yes': 'بلی',
          'No': 'نا',
          'News Have Been deleted': '!خبر هذف شد',
          'News Has Been Added!': '.خبر اضافه شد',
          '     No Data Availabe! \n Please Try Again Later.':
              '     !معلومات وجود ندارد \n     لطفاً باز کوشش کنید',
          'Video News': 'خبرهای ویدیوی',
          'Analysis': 'تحلیل ها',
          'Latest Analysis': 'تحلیل های اخر',
          'Documentaries': 'مستند',
          'Latest Documentaries': 'مستند اخری',
          'Latest Reports': 'راپورهای اخر',
          'Radio Programs': 'برنامه های رادیوي',
          'All Programs': 'برنامه های همه',
          'Latest Programs': 'برنامه های اخر',
          'Reports': 'راپورها',
          'Search Here...': 'در اینجا سرچ کنید',
          'ُView All': 'بازدید همه',
          'Business': 'تجارت',
          'Afghanistan': 'افغانستان',
          'World': 'جهان',
          'Asia': 'اسیاّ',
          'Resource:': ':منبعه',
          'ُTrending News': 'خبرهای عام',
          'ُBreaking News': 'خبرهای عاجل',
          'Politics': 'سیاست',
          'Development': 'پیشرفت',
          'Islam & Culture': 'اسلام/ تمدن',
          'Technology': 'فن اّوری',
          'News': 'خبرها',
          'Hurriyat': 'حوریت',
          'Arabic': 'عربي',
          'Become Our Members': 'دوست ما شوید',
          'Privacy': 'امنیت',
          'Policy': 'روش',
          'Faham Community': 'Faham Community',
          'PUBLISHED IN': 'نشر شده در',
          'In': 'در',
          'Enter a valid email': 'ایمیل ادرس صحی دا وارید کنید',
          'Please Wait....': 'لطفاً صبور باشد',
          'Create New Post': 'فوست جدید کنید',
          'Log in Form ': 'فورم داخیل شدن',
          'Sign Up': 'نو ساختن',
          'Login In': 'داخل شدن',
          'Camera': 'کېمره',
          'Gallery': 'ګالري',
          'Confirm Password': 'تائید نام مخفی',
          'َStatues': 'حالت',
          'Enter Your Statues:': 'حالت خود را داخیل کنید',
          'َJob': 'وظیفه',
          'Enter Your Job:': 'وظیفه خود را داخیل کنید',
          'َBio': 'شهرت',
          'Enter Your Biography:': 'شهرت خود را داخیل کنید',
          'Email': 'ایمل ادرس',
          'Enter User Email:': 'ایمل ادرس را داخیل کنید',
          'last Name': 'نام اخر',
          'Enter Last Name:': 'نام اخر راداخل کنید',
          'Enter First Name': 'نام اول راداخل کنید',
          'First Name': 'نام اول',
          'Sign Up Form': 'فورم اکونت جدید',
          'Enter Password': 'نام مخفی خود را بنویسید',
          'password': 'نام مخفی',
          'Does not have account yet?': 'ایا اکونت ندارید؟',
          'Do you have account?': 'ايا اکونت دارید؟',
          'Choose Profile photo': 'تصویر خود را انتخاب کنید',
          'Movie': 'سینما',
          'Foods': 'خوارک',
          'Religious': 'مذهب',
          'Economic': 'اقتصاد',
          'Historical': 'تاریخ',
          'Geographical': 'جغرافيه',
          'Enter Name:': 'ایمیل ادرس خود رابنویسید',
          'Name': 'نام',
          'Favorites': 'انتخاب شده',
          'Home': 'خانه',
          'Members': 'استفاده کننده',
          'Invite Friends': 'دعوت رفیقان',
          'Language': 'زبان',
          'English': 'انګلش',
          'Posts': 'اعلانونه',
          'Pashto': 'پشتو',
          'Dari': 'دری',
          'Dark Mood': 'حالت تیارکی',
          'Light Mood': 'حالت روشنایی',
          'Help': 'کومک',
          'FeedBack': 'بازدید',
          'About Us': 'درباره ما',
          'Log Out': 'خارج شدن',
          'Login': 'داخل شدن',
          'Sign up': 'نوجورکردن',
          'Faham': 'فهم',
          'Public': 'عام',
          'Sports': 'ورزش',
          'Motivation': 'انګیزشي',
          'Health': 'صحت',
          'Political': 'سیاست',
          'loves': 'محبت',
          'Shares': 'شریک کردن',
          'Views': 'دیدن',
        }
      };
}
